services:
  postgres:
    image: postgres:16-alpine
    container_name: mcp-chat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mcpuser
      POSTGRES_PASSWORD: mcppassword
      POSTGRES_DB: mcpchat
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcpuser -d mcpchat"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-chat-app
    restart: unless-stopped
    ports:
      - "8888:3000"
    environment:
      DATABASE_URL: postgresql://mcpuser:mcppassword@postgres:5432/mcpchat
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      # Mount config directory for hot-reload of model changes
      - ./config:/app/config:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - backend_central-network

volumes:
  postgres_data:
    driver: local

networks:
  backend_central-network:
    external: true
